### ISSUE TITLE
Black out cells

### ISSUE THREAD

**Issue by 0beyer** [UMM-CSci-3601-F24/it-2-virgin-of-the-passion#26]

**Comment by 0beyer** [comment]
when cells are bolded at the edge of the grid, pressing ctrl alone will unbold the cell but not edges

Ctrl clicking the top of the grid will black out the cell, but only boldes the top edge
Ctrl clicking the left of the grid will black out the cell, but only boldes the top & right edge
Ctrl clicking the bottom of the grid will black out the cell, but dosnt bold the left edge
the top right corner is treated as the top of the grid, top& bottom left is treated as left edge of grid, and bottom right is treated as bottom edge of the grid

**Comment by JosieBarber** [comment]
May I ask why you are looking at the edges separately at all like this?
The main thing you need to check is just like "If it is already bolded don't do anything to that edge".

Also why do you have multiple controls instead of just a toggle?

**Comment by 0beyer** [comment]
i dont know what you mean, if your talking abt the useless if statements, i removed them
the problem im facing is a wierd edge case, and i have no clue why its happening

I do not know what you mean abt toggle, but for now my method is incomplete, as ctrl click for undoing the function is not working, if me and nick cannot find a solution, we will use double click with no control probabally, as double click w ctrl is still buggy

**Comment by 0beyer** [comment]
Potential Edge case:
if a cell has 4 adjacent blacked out cells on each side, the middle cells will be blacked out to.
I cannot think of any ways this could be a issue, but we should bring it up to our customer.
